name: sudoku_provider
description: A sudoku grid provider.
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  bloc: ^7.0.0
  equatable: ^2.0.3

dev_dependencies:
  bloc_test: ^8.0.2
  test: ^1.17.9
